- name: Find all log files in the directory
  ansible.builtin.find:
    paths: "/var/log/dirsrv/slapd-supplier1"
    patterns: "access*"
  register: log_files

- name: Copy dslogs script to the target machine
  ansible.builtin.copy:
    src: "./dslogs"
    dest: "/tmp/dslogs"
    mode: "0755"

- name: Parse CSN values from log files using dslogs script
  ansible.builtin.command: "python3 /tmp/dslogs {{ log_files.files | map(attribute='path') | join(' ') }}"
  register: csn_values

- name: Parse CSN value
  set_fact:
    csn_values: "{{ csn_values.stdout }}"

- name: Debug CSN values
  ansible.builtin.debug:
    var: csn_values
