- name: Find all log files in the replication monitoring directory
  ansible.builtin.find:
    paths: "{{ replication_monitoring_log_dir }}"
    patterns: "access*"
  register: log_files

- name: Copy dslogs script to the target machine
  ansible.builtin.copy:
    src: "./files/dslogs.py"
    dest: "/tmp/dslogs.py"
    mode: "0755"

- name: Execute dslogs script and redirect output to file
  ansible.builtin.shell: "python3 /tmp/dslogs.py {{ log_files.files | selectattr('path', 'match', '^/tmp/accesslog' + inventory_hostname | regex_replace('^instance', '') + '$') | map(attribute='path') | join(' ') }} > /tmp/{{ inventory_hostname }}_dslogs_output.json"
  args:
    executable: /bin/bash

- name: Copy dslogs output file to controller with server name in filename
  ansible.builtin.fetch:
    src: "/tmp/{{ inventory_hostname }}_dslogs_output.json"
    dest: "/tmp/{{ inventory_hostname }}_dslogs_output.json"
    flat: yes

- name: Run merge_dslogs script on the controller
  ansible.builtin.command: "python3 ./files/merge_dslogs.py {{ groups['all'] | map('extract', hostvars, ['ansible_hostname']) | map('regex_replace', '^', '/tmp/') | map('regex_replace', '$', '_dslogs_output.json') | join(' ') }}"
  delegate_to: localhost
  run_once: true

