---
- name: Setup Environment for 389 DS Replication Monitoring
  hosts: all
  become: true

  tasks:
    - name: Test connectivity to all hosts
      ansible.builtin.ping:

    - name: Ensure necessary packages are installed
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - python-matplotlib
      delegate_to: localhost
      run_once: true
      when: ansible_os_family == "RedHat"

    - name: Ensure log directory exists
      ansible.builtin.file:
        path: "{{ replication_monitoring_log_dir }}"
        state: directory
        mode: '0755'
